/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthPage: typeof import('./src/components/AuthPage.vue')['default']
    Button: typeof import('primevue/button')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListPacks: typeof import('./src/components/ListPacks.vue')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TrainCard: typeof import('./src/components/TrainCard.vue')['default']
    TrainPage: typeof import('./src/components/TrainPage.vue')['default']
  }
}

// For TSX support
declare global {
  const AuthPage: typeof import('./src/components/AuthPage.vue')['default']
  const Button: typeof import('primevue/button')['default']
  const FloatLabel: typeof import('primevue/floatlabel')['default']
  const HomePage: typeof import('./src/components/HomePage.vue')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const ListPacks: typeof import('./src/components/ListPacks.vue')['default']
  const Password: typeof import('primevue/password')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Select: typeof import('primevue/select')['default']
  const Toast: typeof import('primevue/toast')['default']
  const ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  const TrainCard: typeof import('./src/components/TrainCard.vue')['default']
  const TrainPage: typeof import('./src/components/TrainPage.vue')['default']
}